version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=timetable_db
    volumes:
      - .:/tmp/pg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d timetable_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports: [ "9000:80" ]
    volumes:
      - pg_pgadmin:/var/lib/pgadmin
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  database_spring:
  pg_pgadmin: